on:
  workflow_call:
    inputs:
      release-drafter-config-name:
        description: "Release drafter config name to use, relative to .github/."
        default: release-drafter-config.yml
        required: false
        type: string

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: ${{ inputs.release-drafter-config-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
