on:
  workflow_call:
    secrets:
      mcaf-github-token:
        description: "The github token able to push the changelog to the default branch"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.mcaf-github-token }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.repository.default_branch }}
          commit_message: 'docs(changelog): update changelog'
          file_pattern: CHANGELOG.md

