name: workflow-synchronization

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  REPOSITORIES: |
    schubergphilis/terraform-aws-mcaf-account-baseline
    schubergphilis/terraform-aws-mcaf-aurora
    schubergphilis/terraform-aws-mcaf-avm
    schubergphilis/terraform-aws-mcaf-dynamodb
    schubergphilis/terraform-aws-mcaf-glue-connector
    schubergphilis/terraform-aws-mcaf-landing-zone
    schubergphilis/terraform-aws-mcaf-s3
    schubergphilis/terraform-aws-mcaf-securityhub-findings-manager
    schubergphilis/terraform-aws-mcaf-transit-gateway
    schubergphilis/terraform-aws-mcaf-user
    schubergphilis/terraform-aws-mcaf-workspace
    schubergphilis/terraform-github-mcaf-repository
    schubergphilis/terraform-gitlab-mcaf-project

  WORKFLOW_FILES: |
    sync-root/.github/labels.yaml=.github/labels.yaml
    sync-root/.github/release-drafter-config.yaml=.github/release-drafter-config.yaml
    sync-root/.github/workflows=.github
    sync-root/.pre-commit-config.yaml=.pre-commit-config.yaml
    sync-root/CONTRIBUTING.md=CONTRIBUTING.md
    sync-root/LICENSE=LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Synchronize files
        uses: varunsridharan/action-github-workflow-sync@3.3
        with:
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          COMMIT_MESSAGE: "[SYNC] mcaf-github-workflows"
          GITHUB_TOKEN: ${{ secrets.MCAF_WORKFLOW_SYNCHRONIZATION }}
